# Generated by Django 5.1.6 on 2025-02-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('company_owner', 'Company Owner'), ('manager', 'Manager'), ('tenant', 'Tenant')], max_length=20),
        ),
    ]
