# Generated by Django 5.1.6 on 2025-03-12 01:41

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=core.storage.ProfileImageStorage(), upload_to='profile_images/'),
        ),
    ]
