# Generated by Django 5.1.6 on 2025-03-11 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companymember_role_companyinvitation'),
        ('invoices', '0002_invoice_period_end_invoice_period_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='type',
            field=models.CharField(choices=[('standard', 'Standarta'), ('rent', 'Īres maksa'), ('utility', 'Komunālie maksājumi'), ('maintenance', 'Remontdarbi'), ('fee', 'Papildu maksa'), ('discount', 'Atlaide'), ('other', 'Cits')], default='standard', max_length=50),
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('standard', 'Standarta nodoklis'), ('reduced', 'Samazinātā likme'), ('energy', 'Enerģijas nodoklis'), ('water', 'Ūdens nodoklis'), ('gas', 'Gāzes nodoklis'), ('waste', 'Atkritumu nodoklis'), ('other', 'Cits')], default='standard', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'verbose_name': 'Nodoklis',
                'verbose_name_plural': 'Nodokļi',
            },
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='invoices.tax'),
        ),
    ]
