# Generated by Django 5.1.6 on 2025-02-25 22:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
                ('cadastral_number', models.CharField(blank=True, max_length=100)),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('building_type', models.CharField(choices=[('apartment_building', 'Apartment Building'), ('commercial_building', 'Commercial Building'), ('private_house', 'Private House'), ('mixed_use', 'Mixed Use Building')], max_length=20)),
                ('floor_count', models.IntegerField(help_text='Total number of floors')),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('has_building_water_meter', models.BooleanField(default=False)),
                ('has_building_gas_meter', models.BooleanField(default=False)),
                ('has_building_electricity_meter', models.BooleanField(default=False)),
                ('has_building_heating_meter', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_number', models.CharField(help_text='Apartment/Unit number', max_length=50)),
                ('floor', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.IntegerField()),
                ('unit_type', models.CharField(choices=[('apartment', 'Apartment'), ('office', 'Office'), ('retail', 'Retail Space'), ('warehouse', 'Warehouse'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved')], max_length=20)),
                ('has_water_meter', models.BooleanField(default=False)),
                ('has_gas_meter', models.BooleanField(default=False)),
                ('has_electricity_meter', models.BooleanField(default=False)),
                ('has_heating_meter', models.BooleanField(default=False)),
                ('bathroom_count', models.IntegerField(default=1)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_storage', models.BooleanField(default=False)),
                ('parking_spots', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitMeter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter_type', models.CharField(choices=[('water_cold', 'Cold Water'), ('water_hot', 'Hot Water'), ('gas', 'Gas'), ('electricity', 'Electricity'), ('heating', 'Heating')], max_length=20)),
                ('meter_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reading_date', models.DateField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'ordering': ['-reading_date', '-created_at'],
            },
        ),
    ]
