# Generated by Django 5.1.6 on 2025-02-25 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='property',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unit',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property'),
        ),
        migrations.AddField(
            model_name='unitmeter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='unitmeter',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='properties.unit'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='properties.unitmeter'),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('company', 'address')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('property', 'unit_number')},
        ),
        migrations.AddConstraint(
            model_name='unitmeter',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('unit', 'meter_type'), name='unique_active_meter_type_per_unit'),
        ),
        migrations.AlterUniqueTogether(
            name='unitmeter',
            unique_together={('unit', 'meter_type', 'meter_number')},
        ),
    ]
