# Generated by Django 5.1.6 on 2025-03-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_number',
            field=models.CharField(help_text='Apartment/Unit number', max_length=10),
        ),
    ]
