# Generated by Django 5.1.6 on 2025-03-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_unit_unit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmeter',
            name='tariff',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tarifs par vienu vienību (€)', max_digits=10),
        ),
    ]
