# Generated by Django 5.1.6 on 2025-03-12 01:41

import companies.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=core.storage.CompanyStorage(), upload_to=companies.models.get_company_logo_upload_path),
        ),
    ]
