# Generated by Django 5.1.6 on 2025-03-12 01:41

import core.storage
import inspections.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueimage',
            name='image',
            field=models.ImageField(storage=core.storage.IssueImageStorage(), upload_to=inspections.models.get_report_Issue_image_upload_path),
        ),
    ]
