# Generated by Django 5.1.6 on 2025-03-12 03:01

import core.storage
import inspections.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_issueimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueimage',
            name='image',
            field=models.ImageField(max_length=255, storage=core.storage.IssueImageStorage(), upload_to=inspections.models.get_report_Issue_image_upload_path),
        ),
    ]
